backend/controllers/RunprocessController.php
<?php

namespace backend\controllers;

use Yii;
use backend\models\SysReport;
use backend\models\SysReportSearch;

class RunprocessController extends \yii\web\Controller
{
    public function actionIndex()
    {
    	$searchModel = new SysReportSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
        
    }

    public function actionCallprocess(){
    	try{
    	$request = Yii::$app->request;
    	if ($request->isPost) { 
    		$report_procedure = $request->post('id');
    	 }
    	  $sql =  ' CALL sys_runprocess_one (:report_procedure)' ;
            
            $command = Yii::$app->db->createCommand($sql);
            $command->bindParam(":report_procedure", $report_procedure);
            
            $list = $command->execute();
    	
    	#$procedures=
    	# Yii::$app->db->createCommand("CALL sys_runprocess_one('".$report_procedure."');")->queryone();
    	    } catch(\yii\db\Exception $e){ 
              throw new \yii\web\HttpException(405, 'การประมวลผลมีปัญหา กรุณาตรวจสอบที่ databases'); 
        } 
    	   return $this->render('runprocess', [
            'procedures' => $list,
           
        ]);
    }

}

backend/views/runprocess/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use yii\helpers\Url;

/* @var $this yii\web\View */
/* @var $searchModel backend\models\SysReportSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'รายงานในระบบ';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="sys-report-index">

    <h1><?= Html::encode($this->title) ?></h1>
    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

    <p>
        <?= Html::a('เพิ่มรายงานในระบบ', ['create'], ['class' => 'btn btn-success']) ?>
    </p>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

            'report_id',
            'report_name:ntext',
             'menu_group',
              [
                  'attribute' => 'active',
                  'value'=>function($value) use ($dataProvider){
                  	if($value->active==1){
                  		return 'เปิด';
                  	}else{
                  		return 'ปิด';
                  	}
                  }
              ],           
             'report_procedure',            
           

            ['class' => 'yii\grid\ActionColumn',
            'template'=>' {my_button}',
            'header' => 'ประมวลผล',
				'buttons' => [
				    'my_button' => function ($url, $dataProvider, $key) {
				        // return Html::a('<button type="button" class="btn btn-default" aria-label="Left Align">
				        // 	<span class="glyphicon glyphicon-play-circle"></span></button>',
				        //  ['callprocess' 
            //      #,'id'=>$dataProvider->report_procedure
            //      ,'data'=>[
            //           'method' => 'post',
            //           'params'=>['id'=>$dataProvider->report_procedure],
            //       ]
            //      ]
                  
            //      );
              return Html::a('<button type="button" class="btn btn-default" aria-label="Left Align">
                  <span class="glyphicon glyphicon-play-circle"></span></button>'
                  ,  Url::toRoute('runprocess/callprocess'), [
                'data' => [
                   # 'confirm' => 'Are you sure you want to delete the campaign?',
                     'method' => 'post',
                         'params'=>['id'=>$dataProvider->report_procedure],
                ],
              ]);
				    },
				],
            ],
        
        ],
    ]); ?>

</div>

backend/views/runprocess/runprocess.php
<?php
#var_dump($procedures);
// use yii\helpers\Html;
// use yii\grid\GridView;
// use yii\helpers\Url;
use yii\widgets\Breadcrumbs;

/* @var $this yii\web\View */
/* @var $searchModel backend\models\SysReportSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'รายงานในระบบ';
$this->params['breadcrumbs'][] = $this->title;

echo Breadcrumbs::widget([
    'itemTemplate' => "<li><i>{link}</i></li>\n", // template for all links
    'links' => [
        [
            'label' => 'รายงานในระบบ',
            'url' => ['runprocess/index'],
            'template' => "<li><b>{link}</b></li>\n", // template for this link only
        ],
        
        'ผลการทำงาน',
    ],
]);
?>
<div class="well well-lg">
<?php
if($procedures=1){
echo 'การประมวลผลเสร็จสิ้น';
}else{
echo 'การประมวลผลผิดพลาด';
}

?>
</div>