frontend/modules/report/controllers/CchangwatController.php
<?php


namespace frontend\modules\report\controllers;
use Yii;
use frontend\modules\report\model\Cchangwat;
use frontend\modules\report\model\CchangwatSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use frontend\modules\report\model\Ctambon;
use frontend\modules\report\model\Campur;
use frontend\modules\report\model\Chospital;
use frontend\modules\report\model\SysConfig;


/**
 * CchangwatController implements the CRUD actions for Cchangwat model.
 */
class CchangwatController extends Controller
{
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                ],
            ],
        ];
    }

    /**
     * Lists all Cchangwat models.
     * @return mixed
     */

 
    public function actionLoadtambon($id=null){
        //$id คือ รหัส pk ของอำเภอ
        $tambons = Ctambon::find()
            ->where(['ampurcode'=>$id,'flag_status'=>'0'])
            ->orderBy('tambonname')
            ->all();
        $option = '<option value="">-กรุณาเลือกหน่วยบริการ-</option>';
        foreach($tambons as $d){
            $option .= '<option value="'.$d->tamboncode.'">'
                .$d->tambonname.'</option>';
        }
        echo $option;
    }
    public function actionLoadhospital($id=null){
        //$id คือ รหัส pk ของอำเภอ
        //h.hostype IN('03','07') AND CONCAT(h.provcode,h.distcode)='7307'
        $tambons = Chospital::find()
            ->where('CONCAT(provcode,distcode)=:pcu', [':pcu'=>$id])
            ->andWhere([
            'hostype' => ['03','04','05','06','07','08','12','13','15','18'],
            ])
            //->addParams([':pcu' => $id,':status' => '03'])
            ->orderBy('hoscode')
            ->all();
        $option = '<option value="">-กรุณาเลือกหน่วยบริการ-</option>';
        foreach($tambons as $d){
            $option .= '<option value="'.$d->hoscode.'">'
                .$d->hosname.'</option>';
        }
        echo $option;
    }
    public function actionIndex()
    {
        $searchModel = new CchangwatSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Cchangwat model.
     * @param string $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Cchangwat model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Cchangwat();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->changwatcode]);
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Updates an existing Cchangwat model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param string $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->changwatcode]);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing Cchangwat model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param string $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Cchangwat model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param string $id
     * @return Cchangwat the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Cchangwat::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

frontend/modules/report/controllers/ReportController.php
<?php
namespace frontend\modules\report\controllers;
use Yii;
use yii\data\ArrayDataProvider;
use yii\web\Controller;
use frontend\modules\report\model\SysReport;
use yii\db\Query;
use yii\db\Command;
use yii\db\Connection;
use yii\helpers\Html;
use yii\helpers\BaseUrl;
use yii\helpers\Url;
use  yii\web\Session;
use frontend\modules\report\model\SysConfig;
use frontend\modules\report\model\SysMenuGroup;
use frontend\modules\report\model\Cmastercup;
//use mdm\admin\components\AccessControl;
//use yii\filters\AccessControl;
//use yii\filters\VerbFilter;

class ReportController extends \yii\web\Controller
{
    //   public function behaviors()
    // {
    //     return [
    //         // 'access' => [
    //         //     'class' => AccessControl::className(),
    //         //     'only' => ['logout', 'signup'],
    //         //     'rules' => [
    //         //         [
    //         //             'actions' => ['signup'],
    //         //             'allow' => true,
    //         //             'roles' => ['?'],
    //         //         ],
    //         //         [
    //         //             'actions' => ['logout'],
    //         //             'allow' => true,
    //         //             'roles' => ['@'],
    //         //         ],
    //         //     ],
    //         // ],
    //         'access' => [
    //             'class' => AccessControl::className(),
    //         ],

    //         'verbs' => [
    //             'class' => VerbFilter::className(),
    //             'actions' => [
    //                 'logout' => ['post'],
    //             ],
    //         ],
    //     ];
    // }
  public function operators(){

     $data_notify = (new \yii\db\Query())
              ->select('n.snt_id,n.hospcode,n.distcode,n.hmain,n.report_id,r.report_name,n.report_group,
                        SUM(y_cases)AS y_cases, (SUM(y_cases)/SUM(total))*100 AS percent ')
              ->from('sys_Notifications n')
              ->leftJoin('sys_report r', 'n.report_id=r.report_id')
              ->where($office)
              //->andWhere(['active' => 1])
              ->addParams([':h' => $hospcode])
              
              ->groupBy('report_id')
              ->orderBy(['percent' => SORT_DESC,])
              ->limit(20)
              ->all(\Yii::$app->db);
  }
  public  function actionDev(){
   
    return $this->render('dev',[
     
      ]);
  }
  public  function actionCalldocs(){
    $request = Yii::$app->request;
    if ($request->isPost) {

$docs_ref = $request->post('docs_ref');
$docs_id = $request->post('docs_id');

    }else{
      $docs_ref=null;
      $docs_id=null;
    }
    \yii::setAlias('@pathdocs', 'http://203.157.151.20/eh/backend/web/documents');
    $html_div="
  <iframe class='embed-responsive-item'".
          "src='http://docs.google.com/gview?".
          "url=".Yii::getAlias('@pathdocs').'/'.$docs_ref.'/'.$docs_id."&embedded=true'".
     "frameborder='0'></iframe>";
   return $html_div;
     
      
  }
    public static function chkcup(){
     $listmaincup='';
      $pmodel=SysConfig::find()->select('province_config')->one();
      $provcup=$pmodel['province_config'].'00';
        $datacup=  Yii::$app->dbhdc->createCommand("SELECT * FROM(
                    SELECT hmain,count(hsub)AS hsub,hmainname,hmaintype 
                    FROM cmastercup
                    WHERE province_id = '".$provcup."'
                    GROUP BY hmain
                    )AS cup
                    WHERE cup.hsub > 1;")->queryAll();
            for($i=0;$i<sizeof($datacup);$i++){    
              $listmaincup[]=$datacup[$i]['hmain'];
             } 


        return $listmaincup;
    }
    public function actionIndex()
    {
      $connection = \Yii::$app->db;
      $transaction = $connection->beginTransaction();
try {
      try{

        
        $data_notify=null;$ridnot=null;$notify_topten=null;
        $list_cup=$this->chkcup();
        $chkdata_notify = (new \yii\db\Query())
              ->select('*')
              ->from('sys_Notifications')
              ->all(\Yii::$app->db);
        $chkdata_notify=count($chkdata_notify);
        if($data_notify==null && $chkdata_notify==0){//isguest
              $data_notify = (new \yii\db\Query())
              ->select("report_id,report_name")
              ->from('sys_report')
              ->where(['active' => 1])
              ->limit(20)
              ->all(\Yii::$app->db);
               for($i=0;$i<sizeof($data_notify);$i++){
                $data_notify[$i]['y_cases']=0;
                $data_notify[$i]['percent']=0;
               }//endfor

            }else{
       // $level3=['h05','h07','03','04','08','12','13','15'];
        if(!Yii::$app->user->isGuest){ #'04','08','12','13','15'
         if(Yii::$app->user->identity->level==1){ //admin
           $hospcode=Yii::$app->user->identity->hospcode;
          $s='n.snt_id,n.hospcode,n.distcode,n.hmain,SUM(n.y_cases)AS y_cases,r.report_id, r.report_name, r.s_table';
          $office=' r.active=1';
          $g='report_id';
        }else if(Yii::$app->user->identity->level=='02'){ //ampur
          $hospcode=Yii::$app->user->identity->hospcode;
          $office=' distcode =:h AND r.active=1';
          $s='n.snt_id,n.hospcode,n.distcode,n.hmain,SUM(n.y_cases)AS y_cases,r.report_id, r.report_name, r.s_table';
          $g='report_id';
        }else if(in_array(Yii::$app->user->identity->hospcode, $list_cup, FALSE)||Yii::$app->user->identity->level!='02'
                  ||Yii::$app->user->identity->level!='01'||Yii::$app->user->identity->level!=1){ //hos
        $hospcode=Yii::$app->user->identity->hospcode;
        $s='n.*, r.report_id, r.report_name, r.t_table';
        $office=' hospcode =:h AND r.active=1';
        }else if(in_array(Yii::$app->user->identity->hospcode, $list_cup, TRUE)){ //cup
          $hospcode=Yii::$app->user->identity->hospcode;
          $s='n.snt_id,n.hospcode,n.distcode,n.hmain,SUM(n.y_cases)AS y_cases,r.report_id, r.report_name, r.s_table';
          $office=' hmain =:h AND r.active=1';
          $g='report_id';
        }//endif level  
    	    
       $data_notify = (new \yii\db\Query())
              ->select('n.snt_id,n.hospcode,n.distcode,n.hmain,n.report_id,r.report_name,n.report_group,
                        SUM(y_cases)AS y_cases, (SUM(y_cases)/SUM(total))*100 AS percent ')
              ->from('sys_Notifications n')
              ->leftJoin('sys_report r', 'n.report_id=r.report_id')
              ->where($office)
              //->andWhere(['active' => 1])
              ->addParams([':h' => $hospcode])
              
              ->groupBy('report_id')
              ->orderBy(['percent' => SORT_DESC,])
              ->limit(20)
              ->all(\Yii::$app->db);

             
        

               
       
            
        $num_notify=count($data_notify);
        if($num_notify<=0){
          $data_notify = (new \yii\db\Query())
              ->select('n.snt_id,n.hospcode,n.distcode,n.hmain,n.report_id,r.report_name,n.report_group,
                        SUM(y_cases)AS y_cases, (SUM(y_cases)/SUM(total))*100 AS percent ')
              ->from('sys_Notifications n')
              ->leftJoin('sys_report r', 'n.report_id=r.report_id')
              ->where(['active' => 1])
              //->where($office)
              //->addParams([':h' => $hospcode])
              ->groupBy('report_id')
              ->orderBy(['percent' => SORT_DESC,])
              ->limit(20)
              ->all(\Yii::$app->db);
        }
        if($num_notify<20){
          $limit_report=20-$num_notify;
           for($i=0;$i<sizeof($data_notify);$i++){
               $ridnot[]= $data_notify[$i]['report_id'];
            }   
          $data_notify_push = (new \yii\db\Query())
              ->select('*')
              ->from('sys_report')
               ->where(['NOT IN', 'report_id', $ridnot])
               ->andwhere(['active' => 1])
              // ->addParams([':office' => '08436'])
              // ->groupBy('report_id')
              // ->orderBy(['y_cases' => SORT_DESC,])
              ->limit($limit_report)
              ->all(\Yii::$app->db);
             $ii=1;$num=0;
          for ($i = $num_notify; $i < 20; $i++) {
            //$i_push[]=($num_notify+count($data_notify_push))-19;
            //if($i==18){$ii=$ii+1;}if($ii==2){$num=$num+2;}else{$num=$i;}
            $num=20-$i-1;
              array_push($data_notify, $data_notify[$i]=[
                'snt_id' =>  99, 
                'hospcode' =>  $hospcode, 
                'distcode' =>  '', 
                'hmain' =>  '', 
                'report_id' => $data_notify_push[19-$i]['report_id'], 
                'report_name'=>$data_notify_push[19-$i]['report_name'], 
                'report_group' =>  'test', 
                'y_cases' =>  '0',
                'percent'=>'0' 
                ]);
              }
            }//endif num_notify


            
      }else{
      if($data_notify==null){//isguest
              $data_notify = (new \yii\db\Query())
              ->select('n.snt_id,n.hospcode,n.distcode,n.hmain,n.report_id,r.report_name,n.report_group,
                        SUM(y_cases)AS y_cases, (SUM(y_cases)/SUM(total))*100 AS percent ')
              ->from('sys_Notifications n')
              ->leftJoin('sys_report r', 'n.report_id=r.report_id')
              ->where(['active' => 1])
              //->where($office)
              //->addParams([':h' => $hospcode])
              ->groupBy('report_id')
              ->orderBy(['percent' => SORT_DESC,])
              ->limit(20)
              ->all(\Yii::$app->db);
            }
             
              

            }//endif isguest

     }//endif chkdata_notify


if(!Yii::$app->user->isGuest){ 
   $toptenwhere=null;
              if(!empty($office)){
                $toptenwhere .=' AND '.$office;

            }
     $sql = " SELECT *
                  FROM sys_report r 

frontend/modules/report/views/report/chk.php
<?php
if(!Yii::$app->user->isGuest){
//echo Yii::$app->user->identity->username ;
//echo Yii::$app->user->identity->level ;

}
?>

frontend/modules/report/views/report/dev.php
<?php
use yii\helpers\Url;
use yii\helpers\Html;


?>
<button type="button" class="btn btn-info btn-lg" data-toggle="modal" data-target="#myModal">Open Modal</button>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
  <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  <!-- Modal -->
  <div class="modal fade" id="myModal" role="dialog">
    <div class="modal-dialog modal-lg">
    
      <!-- Modal content-->
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal">&times;</button>
          <h4 class="modal-title">Modal Header</h4>

<button id='link' value="http://203.157.151.20/eh/backend/web/documents/4288e3330b2e365eceed74c27b4c95dd.pdf">Get External Content</button>
<button id='link2' value="http://infolab.stanford.edu/pub/papers/google.pdf">Get External Content</button>
<?php // searchname: $('#link2').val()  ,
$docs='http://infolab.stanford.edu/pub/papers/google.pdf';
echo Html::button('Button 3', [ 'class' => 'btn btn-primary', 
  'onclick' => "(function () {
    $.ajax({
       url: '".Url::toRoute('report/calldocs')."',
       type: 'post',
       data: {
                 searchname: '".$docs."'  , 
               
                 _csrf : '".Yii::$app->request->getCsrfToken()."'
             },
       success: function (data) {
          console.log(data.search);
          $('#docs').html(data);
       }
  });

    })();" ]);
?>
        </div>
        <div class="modal-body"><!-- body -->
        	 <center><div  class="embed-responsive embed-responsive-16by9">
            <div id='docs'>

            </div>
          
 			 </div></center><!-- endcontent -->
        </div><!-- endbody -->
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        </div>
      </div>
      
    </div>
  </div>
  <!-- endModal -->
  
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
<script type="text/javascript">
$(document).ready(function(){
    $("#link").click(function(){

 $.ajax({
       url: '<?php echo Url::toRoute('report/calldocs'); ?>',
       type: 'post',
       data: {
                 searchname: $("#link").val()  , 
                // searchby: $("#link2").val()  , 
                 _csrf : '<?=Yii::$app->request->getCsrfToken()?>'
             },
       success: function (data) {
          console.log(data.search);
          $("#docs").html(data);
       }
  });
});
});
$(document).ready(function(){
    $("#link2").click(function(){

 $.ajax({
       url: '<?php echo Url::toRoute('report/calldocs'); ?>',
       type: 'post',
       data: {
                 searchname: $("#link2").val()  , 
                // searchby: $("#link2").val()  , 
                 _csrf : '<?=Yii::$app->request->getCsrfToken()?>'
             },
       success: function (data) {
          console.log(data.search);
          $("#docs").html(data);
       }
  });
});
});
</script>

frontend/modules/report/views/report/runreport.php
<style type="text/css">


/* Important part */
.modal-dialog{
    overflow-y: initial !important
}
.modal-body{
    height: 350px;
    overflow-y: auto;
}

</style>
<?php
use miloschuman\highcharts\Highcharts;
//use yii\helpers\Html;
use yii\helpers\BaseUrl;
use yii\helpers\Url;
//use kartik\date\DatePicker;
use yii\widgets\ActiveForm;
use kartik\grid\GridView;
use frontend\modules\runreport\model\Sys_report;
use frontend\modules\report\model\Cchangwat;
use frontend\modules\report\model\Campur;
use frontend\modules\report\model\Chospital;
use yii\helpers\ArrayHelper;
use kartik\export\ExportMenu;
use kartik\helpers\Html;
use yii\helpers\Json;

// use frontend\themes\lte\assets\LteAsset;
// LteAsset::register($this);

$this->title = $reportname;
$this->params['breadcrumbs'][] = ['label' => 'รายงาน', 'url' => ['report/notifyall']];
$this->params['breadcrumbs'][] = $this->title;


    try {
     $campur = $_GET['campur'];
     $ctambon = $_GET['ctambon'];
      $ctambon_list = ArrayHelper::map(Chospital::find()
            ->where('CONCAT(provcode,distcode)=:pcu', [':pcu'=>$campur])
            ->andWhere([
            'hostype' => ['03','04','05','06','07','08','12','13','15','18'], 
            ])->all(), 'hoscode', 'hosname');
      } catch (ErrorException $e) {
         // $province = [];
        $cchangwat = [];
      $campur= [];
      $campur_list= [];
      $ctambon= null;
      $ctambon_list= [];
      }

?>
<?php
$files_g = Json::decode($report_docs);
                              if(empty($files_g)){
                                $docs_file_g=null;
                              }else{
                              if(is_array($files_g)){
                                  # $docs_file_g ='เอกสาร : |';
                                   foreach ($files_g as $keyfile_g => $vfile_g) {
                                // $docs_file_g .= 
                                //   'file'.$keyfile_g.'|file_name'.$vfile_g.'|';
                                   $docs_file_g[]=[
                                   'id'=>$keyfile_g,
                                   'name'=>$vfile_g
                                   ];
                                   }
                                   #$docs_file .='|';
                                  # echo $docs_file_g;
                                }//if is_array
                              }//if empty

#var_dump($docs_file_g);
#$this->registerJs("");

    $form = ActiveForm::begin([
    'method'=>'get',
    'action' => Url::to(['report/runreport1', 'r_table'=>$r_table]),
    ]);
    ?>

        <div class="form-group">
        <?= Html::label('อำเภอ','campur');?>
        <?= Html::dropDownList('campur',$campur,
            ArrayHelper::map(Campur::find()
                ->where('changwatcode='.$provincecode)
                ->orderBy('ampurcodefull ASC')
                ->all(),'ampurcodefull','ampurname'),
            [
                'class'=>'form-control',
                'id'=>'campur',
                'prompt'=>'-เลือกอำเภอ-',
                'onchange'=>'
                       $.get("'.Url::toRoute('cchangwat/loadhospital').'",
                        {id:$(this).val()})
                        .done(function(data){
                            $("select#ctambon").html(data);
                       });
                    '
            ]
        );?>
    </div>

   
    <div class="form-grop">
      <?= Html::label('หน่วยบริการ','ctambon');?>
        <?= Html::dropDownList('ctambon',$ctambon,$ctambon_list,[
            'class'=>'form-control',
            'id'=>'ctambon',
            'prompt'=>'-เลือกหน่วยบริการ-',

        ]);?>
            </div><br>
<div class="row">
 <?php echo Html::submitButton('ตกลง', ['class'=>'btn btn-info']); 

        ActiveForm::end();
    ?>


</div> <!-- class="row" -->
    <br><div class="alert alert-success" role="alert">คำนิยาม:: <?=$defination;?></div>
<?php
  

echo '<h2>รายงาน::'.$reportname.'</h2>';

#var_dump($test_r);
#var_dump($rows);
            foreach ($columns as $index => $value) {  

 if($index>0){
             $gridcolumns[]=[
             #'hAlign' => GridView::ALIGN_RIGHT,
             'attribute'=>$value['Field'],
              'value'=>function($data) use ($value) {

                if($value['Field'] =='hosname'){
                  return  Html::a($data['hosname'],['runreport1','ctambon'=>$data['hospcode'],'campur'=>$_GET['campur'],'r_table'=>$_GET['r_table']]);
               }else if($value['Field']=='ampurname'){
                  return  Html::a($data['ampurname'],['runreport1', 'r_table'=>$_GET['r_table'],'campur'=>$data['distcode']]);
               }else if($value['Field']=='date_serv'){
                return Yii::$app->Udf->thDateAbbr($data[$value['Field']]);
               }else{
                  return  $data[$value['Field']];
                }


                
             },
             #กำหนดการแสดงผล ถ้าเลือกหน่วยบริการแล้ว ไม่ต้องแสดง Hoscode 
             'visible'=> (strlen($ctambon) == 5 && $value['Field'] == 'hosname' ? false : true ),
             #กรณีเป็นวันที่ ระบบจะแสดงเป็น format วันที่
             #'format'=>($value['Field'] == 'date_serv' ? 'date' : 'raw' ),
             'format'=>'raw',
             'label'=>$value['Comment']
                       ];             
               }  //endif index   
         }  

?>


<div class="panel panel-primary">
    <div class="panel-heading"><h3><div class="fa fa-folder-open-o"></div> 


  </h3>   </div>
<br><br>
 <?php

echo Highcharts::widget([
   'options' => [
      'credits' => ['enabled' => false],
      'title' => ['text' => ''],
      'xAxis' => [
         'categories' => $hosname
      ],
      'yAxis' => [
         'title' => ['text' => 'ร้อยละ']
      ],
       'legend'=> [
            'reversed'=> true
        ],
      'plotOptions'=> [
            'series'=> [
             'zoneAxis'=> 'y',
      'zones'=> [
            [
                'value'=> 0,
                'color'=> '#00C0EF'
            ],
            [
                'value'=> 2,
                'color'=> '#00A65A'
            ],
            [
                'value'=> 21,
                'color'=> '#F39C12'
            ],
            [
               
                'color'=> '#DD4B39'
            ],
            ],
                'stacking'=> 'normal'
            ]
        ],
      'series' => [
   
        [
        'type'=>'bar',
        'name'=>'เอ๊ะ %',
        'data'=>$percent,
        'color'=> '#FF5722'
        ],
        
      ]
   ]
]);?>
<?php

                 
$fullExportMenu = ExportMenu::widget([
    'dataProvider' => $data,
    'formatter' => ['class' => 'yii\i18n\Formatter','nullDisplay' => ''],
    'columns' => $gridcolumns,
    'target' => ExportMenu::TARGET_BLANK,
    'fontAwesome' => true,
    'pjaxContainerId' => 'kv-pjax-container',
    'dropdownOptions' => [
        'label' => 'Full',
        'class' => 'btn btn-default',
        'itemsBefore' => [
            '<li class="dropdown-header">Export All Data</li>',
        ],
    ],
]);
echo GridView::widget([
    'dataProvider' => $data,
    'formatter' => ['class' => 'yii\i18n\Formatter','nullDisplay' => ''
                   ],
    
    'columns' => $gridcolumns,
    'pjax' => true,
    'pjaxSettings' => ['options' => ['id' => 'kv-pjax-container']],
    'panel' => [
        'type' => GridView::TYPE_PRIMARY,
        'heading' => '<h3 class="panel-title"><i class="glyphicon glyphicon-book"></i> ข้อมูลต้องสงสัย</h3>',
    ],
    // set a label for default menu
    'export' => [
        'label' => 'Page',
        'fontAwesome' => true,
    ],
    // your toolbar can include the additional full export menu
    'toolbar' => [
        '{export}',
        $fullExportMenu,
        // ['content'=>
        //     Html::button('<i class="glyphicon glyphicon-plus"></i>', [
        //         'type'=>'button', 
        //         'title'=>Yii::t('kvgrid', 'Add Book'), 
        //         'class'=>'btn btn-success'
        //     ]) . ' '.
        //     Html::a('<i class="glyphicon glyphicon-repeat"></i>', ['report/runreport1'], [
        //         'data-pjax'=>0, 
        //         'class' => 'btn btn-default', 
        //         'title'=>Yii::t('kvgrid', 'Reset Grid')
        //     ])
        // ],
    ]
]);                     
?>
</div>
  
    <?php if(!Yii::$app->user->isGuest){ ?>
    <section>
<?php  
$sql=[0=>$a_sql,1=>$s_sql,2=>$t_sql];
$sql_name=[0=>'คำสั่งประมวลผลระดับจังหวัด',1=>'คำสั่งประมวลผลระดับอำเภอ',2=>'คำสั่งประมวลผลระดับหน่วยบริการ'];
for ($i=0;$i<3;$i++) {
?>
<button type="button" class="btn btn-danger" data-toggle="modal" 
data-target="#sql<?=$i;?>"><?=$sql_name[$i];?></button>


<!-- Modal -->
  <div class="modal fade" id="sql<?=$i;?>" role="dialog">
    <div class="modal-dialog modal-lg">
    
      <!-- Modal content-->
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal">&times;</button>
          <h4 class="modal-title"><?=$sql_name[$i];?></h4>
          </div>
        <div class="modal-body"><!-- body -->
           <center><div class="embed-responsive embed-responsive-16by9">
          <div id=''>
            <p><?=$sql[$i];?></p>
            </div>
       </div></center><!-- endcontent -->
        </div><!-- endbody -->
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        </div>
      </div>
      
    </div>
  </div>
  <!-- endModal -->


<?php
}
?>
 <button type='button' class='btn btn-warning' data-toggle='modal' 
    data-target='#myModal'>แนวทางแก้ไขเบื้องต้น</button>
  </section>
<?php
}
?>
   


  <!-- Modal -->
  <div class="modal fade" id="myModal" role="dialog">
    <div class="modal-dialog modal-lg">
    
      <!-- Modal content-->
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal">&times;</button>
          <h4 class="modal-title"><?=$reportname;?></h4>
          <?php
          for($i=0;$i<sizeof($docs_file_g);$i++){
          
          echo Html::button($docs_file_g[$i]['name'], [ 'class' => 'btn btn-primary', 
  'onclick' => "(function () {
    $.ajax({
       url: '".Url::toRoute('report/calldocs')."',
       type: 'post',
       data: {
                 docs_id: '".$docs_file_g[$i]['id']."'  ,
                 docs_ref: '".$report_ref."'  , 
               
                 _csrf : '".Yii::$app->request->getCsrfToken()."'
             },
       success: function (data) {
          console.log(data.search);
          $('#docs').html(data);
       }
  });

    })();" ]);
        }
         

          ?>
        </div>
        <div class="modal-body"><!-- body -->
           <center><div class="embed-responsive embed-responsive-16by9">
          <div id='docs'>

            </div>
       </div></center><!-- endcontent -->
        </div><!-- endbody -->
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        </div>
      </div>
      
    </div>
  </div>
  <!-- endModal -->
   

  
  