backend/models/Sysconfigruntime.php
<?php

namespace backend\models;

use Yii;

/**
 * This is the model class for table "sys_config_runtime".
 *
 * @property integer $run_id
 * @property string $run_gid
 * @property integer $run_rid
 * @property string $s_runtime
 * @property string $e_runtime
 * @property string $fiscal_year
 */
class Sysconfigruntime extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'sys_config_runtime';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['run_rid'], 'integer'],
            [['s_runtime', 'e_runtime'], 'safe'],
            [['run_gid'], 'string', 'max' => 15],
           
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'run_id' => 'id',
            'run_gid' => 'ระบบ/กลุ่มรายงาน',
            'run_rid' => 'รายงาน',
            's_runtime' => 'เริ่มวันที่',
            'e_runtime' => 'สิ้นสุดวันที่',
           
        ];
    }
}

backend/controllers/SysconfigruntimeController.php
<?php

namespace backend\controllers;

use Yii;
use backend\models\Sysconfigruntime;
use backend\models\SysconfigruntimeSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * SysconfigruntimeController implements the CRUD actions for Sysconfigruntime model.
 */
class SysconfigruntimeController extends Controller
{
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                ],
            ],
        ];
    }

    /**
     * Lists all Sysconfigruntime models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new SysconfigruntimeSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Sysconfigruntime model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Sysconfigruntime model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionSysruntime(){
        $request = Yii::$app->request;
        if($request->post('Sysconfigruntime')){
            $Sysconfigruntime_arr=$request->post('Sysconfigruntime');
            $s_time=$Sysconfigruntime_arr['s_runtime'];
            $e_time=$Sysconfigruntime_arr['e_runtime'];
        }
        $model = new Sysconfigruntime();
         $sys=$model->find()
                    ->where(['run_gid' => 'root'])
                    ->one();
       if($model->load(Yii::$app->request->post())){
         if(count($sys)>0){
           // $model->e_runtime = 'yii2@framework.com';
             Yii::$app->db->createCommand()
             ->update('sys_config_runtime', [
                's_runtime' => $s_time,
                'e_runtime' => $e_time,
                ], 'run_gid =\'root\' ')
             ->execute();
             }else{
            $model->run_gid = 'root';
             $model->save();
             }
        }//post
       
        return $this->render('sysruntime', [
                'model' => $model,
                'sys'=>$sys
            ]);
    }
    public function actionCreate()
    {
        $model = new Sysconfigruntime();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->run_id]);
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
         
    }

    /**
     * Updates an existing Sysconfigruntime model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);
        if($model->run_gid=='root'){
             return $this->redirect(['sysconfigruntime/sysruntime', 'id' => $model->run_id]);
        }

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->run_id]);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing Sysconfigruntime model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Sysconfigruntime model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Sysconfigruntime the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Sysconfigruntime::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

backend/controllers/SysmenugroupController.php
<?php

namespace backend\controllers;

use Yii;
use backend\models\SysMenuGroup;
use backend\models\SysMenuGroupSearch;
use backend\models\SysReport;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * SysmenugroupController implements the CRUD actions for SysMenuGroup model.
 */
class SysmenugroupController extends Controller
{
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                ],
            ],
        ];
    }

    /**
     * Lists all SysMenuGroup models.
     * @return mixed
     */
    public function actionLoadgroup($id=null){
        $items = SysReport::find()
            ->where(['menu_group'=>$id])
            ->orderBy('report_id')
            ->all();
        $option = '<option value="">-เลือกรายงาน-</option>';
        foreach($items as $d){
            $option .= '<option value="'.$d->report_id.'">'
                .$d->report_name.'</option>';
        }
        echo $option;
    }
    public function actionIndex()
    {
        $searchModel = new SysMenuGroupSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single SysMenuGroup model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new SysMenuGroup model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new SysMenuGroup();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->muid]);
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Updates an existing SysMenuGroup model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->muid]);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing SysMenuGroup model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the SysMenuGroup model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return SysMenuGroup the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = SysMenuGroup::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

backend/views/sysconfigruntime/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

use yii\helpers\ArrayHelper;
use yii\helpers\BaseUrl;
use yii\helpers\Url;
use backend\models\SysMenuGroup;

use kartik\datecontrol\Module;
use kartik\datecontrol\DateControl;

/* @var $this yii\web\View */
/* @var $model backend\models\Sysconfigruntime */
/* @var $form yii\widgets\ActiveForm */
 try {

     $group = $_GET['group'];
    # $piname = $_GET['piname'];
      $item_list = ArrayHelper::map( SysReport::find()
            ->where(['menu_group'=>$group])
            ->orderBy('report_id')
            ->all(),'report_id','report_name');
      } catch (ErrorException $e) {
      $group= [];
     # $piname= null;
      $item_list= [];
      }
?>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
<script>
$(document).ready(function(){
    $("#divreport").hide();
    $("#hide").click(function(){
        $("#divreport").hide();
    });
    $("#show").click(function(){
        $("#divreport").show();
    });
});
</script>

<div class="sysconfigruntime-form">
  <div class="btn-group btn-group-justified">
    <?php if(!Yii::$app->request->get('id')){ ?>
  <a href="<?=Url::to(['sysconfigruntime/sysruntime']);?>" class="btn btn-default">ตั้งค่าระบบหลัก</a>
   <?php } ?>
  <a href="#" id='hide' class="btn btn-default">ตั้งค่าแบบกลุ่มรายงาน</a>
  <a href="#" id='show' class="btn btn-default">ตั้งค่าแบบรายตัวรายงาน</a>
</div>

    <?php $form = ActiveForm::begin(); ?>

    

   
        <?php 
        echo $form->field($model, 'run_gid')
             ->dropDownList(
            ArrayHelper::map(SysMenuGroup::find()
                ->all(),'mucode','muname'),
            [
                'class'=>'form-control',
                'id'=>'group',
                'prompt'=>'-เลือกประเภท-',
                'onchange'=>'
                       $.get("'.Url::toRoute('sysmenugroup/loadgroup').'",
                        {id:$(this).val()})
                        .done(function(data){
                            $("select#report").html(data);
                       });
                    '
            ]
        );
        ?>
        <div id='divreport'>
        <?= $form->field($model, 'run_rid')
             ->dropDownList($item_list,[
            
            'id'=>'report',
            'prompt'=>'-เลือกรายงาน-'

        ]);

              ?>
            </div>


    <?= 
     $form->field($model, 's_runtime')->widget(DateControl::classname(), [
    'displayFormat' => 'php:d-m-Y',
    'type'=>DateControl::FORMAT_DATE
]);
    ?>
    <?= 
     $form->field($model, 'e_runtime')->widget(DateControl::classname(), [
    'displayFormat' => 'php:d-m-Y',
    'type'=>DateControl::FORMAT_DATE
]);
    ?>

    <div class="form-group">
        <?= Html::submitButton($model->isNewRecord ? 'บันทึก' : 'Update', ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

backend/views/sysconfigruntime/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model backend\models\SysconfigruntimeSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="sysconfigruntime-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'run_id') ?>

    <?= $form->field($model, 'run_gid') ?>

    <?= $form->field($model, 'run_rid') ?>

    <?= $form->field($model, 's_runtime') ?>

    <?= $form->field($model, 'e_runtime') ?>

    <?php // echo $form->field($model, 'fiscal_year') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

backend/views/sysconfigruntime/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model backend\models\Sysconfigruntime */

$this->title = 'ตั้งค่าการประมวลผล';
$this->params['breadcrumbs'][] = ['label' => 'รายการประมวลผลในระบบ', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="sysconfigruntime-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

backend/views/sysconfigruntime/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use backend\models\SysMenuGroup;
use backend\models\SysReport;

/* @var $this yii\web\View */
/* @var $searchModel backend\models\SysconfigruntimeSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'รายการประมวลผลในระบบ';
$this->params['breadcrumbs'][] = $this->title;
// if($model->run_rid && $model->run_gid){
// $model_g = SysReport::find()
//     ->where('report_id = :report_id', [':report_id' => $model->run_rid])
//     ->one();
// $con_name='รายงาน '.$model_g['report_name'];
// }else if($model->run_gid){
// $model_g = SysMenuGroup::find()
//     ->where('mucode = :mucode', [':mucode' => $model->run_gid])
//     ->one();
//     $con_name='กลุ่มรายงาน '.$model_g['muname'];
// }else if($model->run_rid){
// $model_g = SysReport::find()
//     ->where('report_id = :report_id', [':report_id' => $model->run_rid])
//     ->one();
//     $con_name='รายงาน '.$model_g['report_name'];
// }
?>
<div class="sysconfigruntime-index">

    <h1><?= Html::encode($this->title) ?></h1>
    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

    <p>
        <?= Html::a('ตั้งค่าการประมวลผล', ['create'], ['class' => 'btn btn-success']) ?>
    </p>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],
            'run_id',
                [
                  'attribute' => 'run_gid',
                  'value'=>function($value) use ($dataProvider){
                    if($value->run_gid=='root'){
                        return 'ระบบหลัก';
                    }else if(!IS_NULL($value->run_gid)&&!IS_NULL($value->run_rid)){
                        return 'รายงาน '.SysReport::getname($value->run_rid);
                    }else if(IS_NULL($value->run_gid)){
                        if(!IS_NULL($value->run_rid)){
                            return 'รายงาน '.SysReport::getname($value->run_rid);
                        }
                        return '';
                    }else{
                    return  'กลุ่ม '.SysMenuGroup::getname($value->run_gid);
                    }
                  }
                ],
            
            // 'run_gid',
            // 'run_rid',
            's_runtime',
            'e_runtime',
     

            ['class' => 'yii\grid\ActionColumn'],
        ],
    ]); ?>

</div>

backend/views/sysconfigruntime/sysruntime.php
<?php

use yii\helpers\Html;
use yii\helpers\Url;
use kartik\datecontrol\Module;
use kartik\datecontrol\DateControl;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model backend\models\Sysconfigruntime */

$this->title = ' ตั้งค่าการประมวลผล';
$this->params['breadcrumbs'][] = ['label' => 'ตั้งค่าการประมวลผล', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>



    <h1><?= Html::encode($this->title) ?></h1>
<div class="sysconfigruntime-form">
  <div class="btn-group btn-group-justified">
  <a href="<?=Url::to(['sysconfigruntime/sysruntime']);?>" class="btn btn-default active">ตั้งค่าระบบหลัก</a>
  <?php if(!Yii::$app->request->get('id')){ ?>
  <a href="<?=Url::to(['sysconfigruntime/create']);?>" id='hide' class="btn btn-default">ตั้งค่าแบบเฉพาะ</a>
  <?php } ?>
</div>

 <?php 
 $form = ActiveForm::begin();
	//var_dump($sys);

#var_dump(Yii::$app->request->post('Sysconfigruntime'));
  ?>
    <?= 
     $form->field($model, 's_runtime')->widget(DateControl::classname(), [
    'displayFormat' => 'php:d-m-Y',
    'type'=>DateControl::FORMAT_DATE
]);
    ?>
    <?= 
     $form->field($model, 'e_runtime')->widget(DateControl::classname(), [
    'displayFormat' => 'php:d-m-Y',
    'type'=>DateControl::FORMAT_DATE
]);
    ?>    

 <div class="form-group">
        <?= Html::submitButton($model->isNewRecord ? 'บันทึก' : 'บันทึก', ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
    </div>
<?php ActiveForm::end(); ?>
</div>

backend/views/sysconfigruntime/update.php
<?php

use yii\helpers\Html;
use backend\models\SysMenuGroup;
use backend\models\SysReport;

/* @var $this yii\web\View */
/* @var $model backend\models\Sysconfigruntime */
if($model->run_rid && $model->run_gid){
$model_g = SysReport::find()
	->where('report_id = :report_id', [':report_id' => $model->run_rid])
	->one();
$con_name='รายงาน '.$model_g['report_name'];
}else if($model->run_gid){
$model_g = SysMenuGroup::find()
	->where('mucode = :mucode', [':mucode' => $model->run_gid])
	->one();
	$con_name='กลุ่มรายงาน '.$model_g['muname'];
}else if($model->run_rid){
$model_g = SysReport::find()
	->where('report_id = :report_id', [':report_id' => $model->run_rid])
	->one();
	$con_name='รายงาน '.$model_g['report_name'];
}
$this->title = 'ตั้งค่าการประมวลผล '.': '.$con_name;
$this->params['breadcrumbs'][] = ['label' => 'Sysconfigruntimes', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->run_id, 'url' => ['view', 'id' => $model->run_id]];
$this->params['breadcrumbs'][] = 'Update';
#var_dump($model);
?>
<div class="sysconfigruntime-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

backend/views/sysconfigruntime/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model backend\models\Sysconfigruntime */

$this->title = $model->run_id;
$this->params['breadcrumbs'][] = ['label' => 'Sysconfigruntimes', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="sysconfigruntime-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Update', ['update', 'id' => $model->run_id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Delete', ['delete', 'id' => $model->run_id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Are you sure you want to delete this item?',
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'run_id',
            'run_gid',
            'run_rid',
            's_runtime',
            'e_runtime',
            
        ],
    ]) ?>

</div>